model:
  num_classes: 80
  in_channels: 3
  neck_channels: 256
  msb_variant: yolov8_s
  use_lem: false
  lem_channels: 32
  fusion_gate_reduction: 8
  tdsf_spg_reduction: 8
  tdsf_dpg_kernels: [3, 5, 7]
  rfb_channels: 512
  rfb_expand_ratio: 1.0
  rfb_dilations: [3, 5]
  detect_feature_strides: [4, 8, 16]
  stride_init_image_size: 256
  loss_hyperparameters:
    box: 7.5
    cls: 0.5
    dfl: 1.5
